package demo.rules.experience;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Disruption implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Airline Code")
   private java.lang.String airlineCode;
   @org.kie.api.definition.type.Label(value = "Delay In Minutes")
   private java.lang.Long delayInMinutes;
   @org.kie.api.definition.type.Label(value = "Flight Number")
   private java.lang.String flightNumber;
   @org.kie.api.definition.type.Label(value = "Impact Rating")
   private java.lang.String impactRating;

   public Disruption()
   {
   }
   
   public Disruption(String impactRating, String airlineCode, String flightNumber, Long delayInMinutes)
   {
       this.impactRating = impactRating;
       this.airlineCode = airlineCode;
       this.flightNumber = flightNumber;
       this.delayInMinutes = delayInMinutes;
   }

   public java.lang.String getAirlineCode()
   {
      return this.airlineCode;
   }

   public void setAirlineCode(java.lang.String airlineCode)
   {
      this.airlineCode = airlineCode;
   }

   public java.lang.Long getDelayInMinutes()
   {
      return this.delayInMinutes;
   }

   public void setDelayInMinutes(java.lang.Long delayInMinutes)
   {
      this.delayInMinutes = delayInMinutes;
   }

   public java.lang.String getFlightNumber()
   {
      return this.flightNumber;
   }

   public void setFlightNumber(java.lang.String flightNumber)
   {
      this.flightNumber = flightNumber;
   }

   public java.lang.String getImpactRating()
   {
      return this.impactRating;
   }

   public void setImpactRating(java.lang.String impactRating)
   {
      this.impactRating = impactRating;
   }

   public Disruption(java.lang.String airlineCode,
         java.lang.Long delayInMinutes, java.lang.String flightNumber,
         java.lang.String impactRating)
   {
      this.airlineCode = airlineCode;
      this.delayInMinutes = delayInMinutes;
      this.flightNumber = flightNumber;
      this.impactRating = impactRating;
   }

}