package demo.rules.experience;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Flight implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Airline Code")
   private java.lang.String airline_code;
   @org.kie.api.definition.type.Label(value = "Flight Number")
   private java.lang.String flight_number;
   @org.kie.api.definition.type.Label(value = "Operational Status")
   private java.lang.String operational_status;
   @org.kie.api.definition.type.Label(value = "Schedule Arrival Loca")
   private java.lang.String schedule_arrival_local;
   @org.kie.api.definition.type.Label(value = "Schedule Departure Local")
   private java.lang.String schedule_departure_local;

   public Flight()
   {
   }

   public java.lang.String getAirline_code()
   {
      return this.airline_code;
   }

   public void setAirline_code(java.lang.String airline_code)
   {
      this.airline_code = airline_code;
   }

   public java.lang.String getFlight_number()
   {
      return this.flight_number;
   }

   public void setFlight_number(java.lang.String flight_number)
   {
      this.flight_number = flight_number;
   }

   public java.lang.String getOperational_status()
   {
      return this.operational_status;
   }

   public void setOperational_status(java.lang.String operational_status)
   {
      this.operational_status = operational_status;
   }

   public java.lang.String getSchedule_arrival_local()
   {
      return this.schedule_arrival_local;
   }

   public void setSchedule_arrival_local(
         java.lang.String schedule_arrival_local)
   {
      this.schedule_arrival_local = schedule_arrival_local;
   }

   public java.lang.String getSchedule_departure_local()
   {
      return this.schedule_departure_local;
   }

   public void setSchedule_departure_local(
         java.lang.String schedule_departure_local)
   {
      this.schedule_departure_local = schedule_departure_local;
   }

   public Flight(java.lang.String airline_code,
         java.lang.String flight_number,
         java.lang.String operational_status,
         java.lang.String schedule_arrival_local,
         java.lang.String schedule_departure_local)
   {
      this.airline_code = airline_code;
      this.flight_number = flight_number;
      this.operational_status = operational_status;
      this.schedule_arrival_local = schedule_arrival_local;
      this.schedule_departure_local = schedule_departure_local;
   }

}